ip: '192.168.46.50' #crate IP address
crate_path: /home/nfs/pastika/Downloads/net-snmp-5.9.4/mibs #path to the crate MIBs
snmp_path: /home/nfs/pastika/Downloads/net-snmp-5.9.4/apps #path to the snmp commands
ramp_rate: 30 #V/s global ramp and deramp rates. it will apply the "-1" in the program, so this number can be positive. 
lappds_in_use: ['86','157'] #labels for the LAPPDs in use, referencing the settings below
debug: False #debug mode for the python program, will only print commands, not execute (for now)
#when the photocathode is set to "off", we reverse bias it relative to the MCP1 
#as even with very small voltages, it is easy to get some photoelectrons. 
pc_off_bias: -0.5 #Volts

#LAPPD settings for 86
l86:

  #SETPOINTS:
  #You can change these within the file, save, and "re-load" within the
  #python program and it will reparse the setpoints as new targets. 
  #Based on the divider spreadsheet on the LAPPD google drive, both LAPPDs
  #and both HV circuit configurations result in the same voltage setpoints
  #for roughly the same MCP voltage drops (slight differences)
  set_v: {'pc': 2150, 'mcp1': 2100, 'mcp2': 1050} #~850V per plate
  #set_v: {'pc': 2210, 'mcp1': 2200, 'mcp2': 1100} #~900V per plate
  #set_v: {'pc': 0, 'mcp1': 0, 'mcp2': 0} #Convenient ramp down to 0V


  max_v: {'pc': 2400, 'mcp1': 2300, 'mcp2': 1200} #software maxima for the voltages
  #Below is the operation current limiter, so we can set this based on expectations
  #from the spice simulation of the divider. If you operate with a parallel resistance
  #to the MCPs, then the current settings should be different. 
  #The photocathode supply should not draw more than 10 uA, unless being clamped
  #by the zener (i.e. 200V above the MCP1). Units are in amps
  #max_i = {'pc': 10e-6, 'mcp1':600e-6, 'mcp2': 300e-6}  #for parallel config
  max_i: {'pc': 10e-6, 'mcp1': 200e-6, 'mcp2': 100e-6} #for series config


l157:
  set_v: {'pc': 2150, 'mcp1': 2100, 'mcp2': 1050} #~850V per plate
  #set_v: {'pc': 2210, 'mcp1': 2200, 'mcp2': 1100} #~900V per plate
  #set_v: {'pc': 0, 'mcp1': 0, 'mcp2': 0} #Convenient ramp down to 0V

  max_v: {'pc': 2400, 'mcp1': 2300, 'mcp2': 1200} #software maxima for the voltages
  #max_i = {'pc': 10e-6, 'mcp1':600e-6, 'mcp2': 300e-6}  #for parallel config
  max_i: {'pc': 10e-6, 'mcp1': 200e-6, 'mcp2': 100e-6} #for series config
